### PR TITLE
This commit enables indentation in .editorconfig file so that indentation rules can be enforced

### PR DESCRIPTION
**Pull request by Daniel-Jacob**

### CODE REVIEW

**Review by rachelcarmena — APPROVED** [review]
Awesome, thanks @Daniel-Jacob :raised_hands:

**Review by i-walker — APPROVED** [review]
👏 Thanks @Daniel-Jacob

**Comment by Daniel-Jacob** [comment]
> 👏 Thanks @Daniel-Jacob

Welcome! Question I see I don’t have write access to the arrow repositories. Is this something that can be arranged?:)

**Comment by rachelcarmena** [comment]
> Welcome! Question I see I don’t have write access to the arrow repositories. Is this something that can be arranged?:)

Hi @Daniel-Jacob , I think you're wondering how to fix the conflicts. 

Please, follow these steps for syncing your fork and they will be able to be solved in your branch:

* https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

As soon as new commits are found in your branch, this pull request will be updated automatically.

Thank you so much!!

**Comment by Daniel-Jacob** [comment]
> > Welcome! Question I see I don’t have write access to the arrow repositories. Is this something that can be arranged?:)
> 
> Hi @Daniel-Jacob , I think you're wondering how to fix the conflicts.
> 
> Please, follow these steps for syncing your fork and they will be able to be solved in your branch:
> 
> * https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork
> 
> As soon as new commits are found in your branch, this pull request will be updated automatically.
> 
> Thank you so much!!

That was already done, however I cannot merge the PR since I don't have write access?

**Pull request merged**
