### PR TITLE
Deprecate @higherkind & @extension for MapK

### PR DESCRIPTION
**Pull request by nomisRev**
- [x] Eq (EqK)
- [x] Hash
- [x] Show
- [x] Semigroup
- [x] Monoid
- [x] Functor    
- [x] Apply
- [x] Applicative
- [x] Traverse
- [x] Foldable
- [x] Alternative
- [x] MonadFilter
- [x] Semialign
- [x] Unalign
- [x] Zip
- [x] Unzip

### CODE REVIEW

**Comment by nomisRev** [comment]
Foldable waiting on merging #276.

**Comment by nomisRev** [comment]
Blocked by:

> FAILURE: Build failed with an exception.
> * What went wrong:
Execution failed for task ':arrow-core:kaptKotlin'.
> \> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > \> java.lang.reflect.InvocationTargetException (no error message)
   
Debugging suggestions welcome! Tried `-info` & `-debug` but without much success.

**Comment by nomisRev** [comment]
Blocked by #291

**Review by rachelcarmena — APPROVED** [review]
:tada:

**Review by danimontoya — APPROVED** [review]
OMG, good job simon!! 🚀  I hope `set` is not that big haha 💪

**Review by raulraja — APPROVED** [review]
thanks @nomisRev and everyone involved in this massive effort !

**Pull request merged**
